import type { RegionInfo } from '../types'

export const SE_BASE = 'https://auktionstorget.kronofogden.se'
export const COUNTRY = 'se'
export const PLATFORM_ID = 'se-kronofogden'

/** Official Swedish first-level administrative regions (län). Statistics
 * Sweden lists 21 counties and 290 municipalities for the current 2026
 * division; Kronofogden exposes only Kommun per listing, so list crawls map
 * Kommun -> län locally before region filtering. */
export const SE_REGIONS: readonly RegionInfo[] = [
  { code: 'stockholm', name: 'Stockholm' },
  { code: 'uppsala', name: 'Uppsala' },
  { code: 'sodermanland', name: 'Södermanland' },
  { code: 'ostergotland', name: 'Östergötland' },
  { code: 'jonkoping', name: 'Jönköping' },
  { code: 'kronoberg', name: 'Kronoberg' },
  { code: 'kalmar', name: 'Kalmar' },
  { code: 'gotland', name: 'Gotland' },
  { code: 'blekinge', name: 'Blekinge' },
  { code: 'skane', name: 'Skåne' },
  { code: 'halland', name: 'Halland' },
  { code: 'vastra-gotaland', name: 'Västra Götaland' },
  { code: 'varmland', name: 'Värmland' },
  { code: 'orebro', name: 'Örebro' },
  { code: 'vastmanland', name: 'Västmanland' },
  { code: 'dalarna', name: 'Dalarna' },
  { code: 'gavleborg', name: 'Gävleborg' },
  { code: 'vasternorrland', name: 'Västernorrland' },
  { code: 'jamtland', name: 'Jämtland' },
  { code: 'vasterbotten', name: 'Västerbotten' },
  { code: 'norrbotten', name: 'Norrbotten' },
] as const

export const SE_COUNTY_BY_MUNICIPALITY: Record<string, string> = {
  // Stockholm
  'Upplands Väsby': 'Stockholm',
  'Vallentuna': 'Stockholm',
  'Österåker': 'Stockholm',
  'Värmdö': 'Stockholm',
  'Järfälla': 'Stockholm',
  'Ekerö': 'Stockholm',
  'Huddinge': 'Stockholm',
  'Botkyrka': 'Stockholm',
  'Salem': 'Stockholm',
  'Haninge': 'Stockholm',
  'Tyresö': 'Stockholm',
  'Upplands-Bro': 'Stockholm',
  'Nykvarn': 'Stockholm',
  'Täby': 'Stockholm',
  'Danderyd': 'Stockholm',
  'Sollentuna': 'Stockholm',
  'Stockholm': 'Stockholm',
  'Södertälje': 'Stockholm',
  'Nacka': 'Stockholm',
  'Sundbyberg': 'Stockholm',
  'Solna': 'Stockholm',
  'Lidingö': 'Stockholm',
  'Vaxholm': 'Stockholm',
  'Norrtälje': 'Stockholm',
  'Sigtuna': 'Stockholm',
  'Nynäshamn': 'Stockholm',
  // Uppsala
  'Håbo': 'Uppsala',
  'Älvkarleby': 'Uppsala',
  'Knivsta': 'Uppsala',
  'Heby': 'Uppsala',
  'Tierp': 'Uppsala',
  'Uppsala': 'Uppsala',
  'Enköping': 'Uppsala',
  'Östhammar': 'Uppsala',
  // Södermanland
  'Vingåker': 'Södermanland',
  'Gnesta': 'Södermanland',
  'Nyköping': 'Södermanland',
  'Oxelösund': 'Södermanland',
  'Flen': 'Södermanland',
  'Katrineholm': 'Södermanland',
  'Eskilstuna': 'Södermanland',
  'Strängnäs': 'Södermanland',
  'Trosa': 'Södermanland',
  // Östergötland
  'Ödeshög': 'Östergötland',
  'Ydre': 'Östergötland',
  'Kinda': 'Östergötland',
  'Boxholm': 'Östergötland',
  'Åtvidaberg': 'Östergötland',
  'Finspång': 'Östergötland',
  'Valdemarsvik': 'Östergötland',
  'Linköping': 'Östergötland',
  'Norrköping': 'Östergötland',
  'Söderköping': 'Östergötland',
  'Motala': 'Östergötland',
  'Vadstena': 'Östergötland',
  'Mjölby': 'Östergötland',
  // Jönköping
  'Aneby': 'Jönköping',
  'Gnosjö': 'Jönköping',
  'Mullsjö': 'Jönköping',
  'Habo': 'Jönköping',
  'Gislaved': 'Jönköping',
  'Vaggeryd': 'Jönköping',
  'Jönköping': 'Jönköping',
  'Nässjö': 'Jönköping',
  'Värnamo': 'Jönköping',
  'Sävsjö': 'Jönköping',
  'Vetlanda': 'Jönköping',
  'Eksjö': 'Jönköping',
  'Tranås': 'Jönköping',
  // Kronoberg
  'Uppvidinge': 'Kronoberg',
  'Lessebo': 'Kronoberg',
  'Tingsryd': 'Kronoberg',
  'Alvesta': 'Kronoberg',
  'Älmhult': 'Kronoberg',
  'Markaryd': 'Kronoberg',
  'Växjö': 'Kronoberg',
  'Ljungby': 'Kronoberg',
  // Kalmar
  'Högsby': 'Kalmar',
  'Torsås': 'Kalmar',
  'Mörbylånga': 'Kalmar',
  'Hultsfred': 'Kalmar',
  'Mönsterås': 'Kalmar',
  'Emmaboda': 'Kalmar',
  'Kalmar': 'Kalmar',
  'Nybro': 'Kalmar',
  'Oskarshamn': 'Kalmar',
  'Västervik': 'Kalmar',
  'Vimmerby': 'Kalmar',
  'Borgholm': 'Kalmar',
  // Gotland
  'Gotland': 'Gotland',
  // Blekinge
  'Olofström': 'Blekinge',
  'Karlskrona': 'Blekinge',
  'Ronneby': 'Blekinge',
  'Karlshamn': 'Blekinge',
  'Sölvesborg': 'Blekinge',
  // Skåne
  'Svalöv': 'Skåne',
  'Staffanstorp': 'Skåne',
  'Burlöv': 'Skåne',
  'Vellinge': 'Skåne',
  'Östra Göinge': 'Skåne',
  'Örkelljunga': 'Skåne',
  'Bjuv': 'Skåne',
  'Kävlinge': 'Skåne',
  'Lomma': 'Skåne',
  'Svedala': 'Skåne',
  'Skurup': 'Skåne',
  'Sjöbo': 'Skåne',
  'Hörby': 'Skåne',
  'Höör': 'Skåne',
  'Tomelilla': 'Skåne',
  'Bromölla': 'Skåne',
  'Osby': 'Skåne',
  'Perstorp': 'Skåne',
  'Klippan': 'Skåne',
  'Åstorp': 'Skåne',
  'Båstad': 'Skåne',
  'Malmö': 'Skåne',
  'Lund': 'Skåne',
  'Landskrona': 'Skåne',
  'Helsingborg': 'Skåne',
  'Höganäs': 'Skåne',
  'Eslöv': 'Skåne',
  'Ystad': 'Skåne',
  'Trelleborg': 'Skåne',
  'Kristianstad': 'Skåne',
  'Simrishamn': 'Skåne',
  'Ängelholm': 'Skåne',
  'Hässleholm': 'Skåne',
  // Halland
  'Hylte': 'Halland',
  'Halmstad': 'Halland',
  'Laholm': 'Halland',
  'Falkenberg': 'Halland',
  'Varberg': 'Halland',
  'Kungsbacka': 'Halland',
  // Västra Götaland
  'Härryda': 'Västra Götaland',
  'Partille': 'Västra Götaland',
  'Öckerö': 'Västra Götaland',
  'Stenungsund': 'Västra Götaland',
  'Tjörn': 'Västra Götaland',
  'Orust': 'Västra Götaland',
  'Sotenäs': 'Västra Götaland',
  'Munkedal': 'Västra Götaland',
  'Tanum': 'Västra Götaland',
  'Dals-Ed': 'Västra Götaland',
  'Färgelanda': 'Västra Götaland',
  'Ale': 'Västra Götaland',
  'Lerum': 'Västra Götaland',
  'Vårgårda': 'Västra Götaland',
  'Bollebygd': 'Västra Götaland',
  'Grästorp': 'Västra Götaland',
  'Essunga': 'Västra Götaland',
  'Karlsborg': 'Västra Götaland',
  'Gullspång': 'Västra Götaland',
  'Tranemo': 'Västra Götaland',
  'Bengtsfors': 'Västra Götaland',
  'Mellerud': 'Västra Götaland',
  'Lilla Edet': 'Västra Götaland',
  'Mark': 'Västra Götaland',
  'Svenljunga': 'Västra Götaland',
  'Herrljunga': 'Västra Götaland',
  'Vara': 'Västra Götaland',
  'Götene': 'Västra Götaland',
  'Tibro': 'Västra Götaland',
  'Töreboda': 'Västra Götaland',
  'Göteborg': 'Västra Götaland',
  'Mölndal': 'Västra Götaland',
  'Kungälv': 'Västra Götaland',
  'Lysekil': 'Västra Götaland',
  'Uddevalla': 'Västra Götaland',
  'Strömstad': 'Västra Götaland',
  'Vänersborg': 'Västra Götaland',
  'Trollhättan': 'Västra Götaland',
  'Alingsås': 'Västra Götaland',
  'Borås': 'Västra Götaland',
  'Ulricehamn': 'Västra Götaland',
  'Åmål': 'Västra Götaland',
  'Mariestad': 'Västra Götaland',
  'Lidköping': 'Västra Götaland',
  'Skara': 'Västra Götaland',
  'Skövde': 'Västra Götaland',
  'Hjo': 'Västra Götaland',
  'Tidaholm': 'Västra Götaland',
  'Falköping': 'Västra Götaland',
  // Värmland
  'Kil': 'Värmland',
  'Eda': 'Värmland',
  'Torsby': 'Värmland',
  'Storfors': 'Värmland',
  'Hammarö': 'Värmland',
  'Munkfors': 'Värmland',
  'Forshaga': 'Värmland',
  'Grums': 'Värmland',
  'Årjäng': 'Värmland',
  'Sunne': 'Värmland',
  'Karlstad': 'Värmland',
  'Kristinehamn': 'Värmland',
  'Filipstad': 'Värmland',
  'Hagfors': 'Värmland',
  'Arvika': 'Värmland',
  'Säffle': 'Värmland',
  // Örebro
  'Lekeberg': 'Örebro',
  'Laxå': 'Örebro',
  'Hallsberg': 'Örebro',
  'Degerfors': 'Örebro',
  'Hällefors': 'Örebro',
  'Ljusnarsberg': 'Örebro',
  'Örebro': 'Örebro',
  'Kumla': 'Örebro',
  'Askersund': 'Örebro',
  'Karlskoga': 'Örebro',
  'Nora': 'Örebro',
  'Lindesberg': 'Örebro',
  // Västmanland
  'Skinnskatteberg': 'Västmanland',
  'Surahammar': 'Västmanland',
  'Kungsör': 'Västmanland',
  'Hallstahammar': 'Västmanland',
  'Norberg': 'Västmanland',
  'Västerås': 'Västmanland',
  'Sala': 'Västmanland',
  'Fagersta': 'Västmanland',
  'Köping': 'Västmanland',
  'Arboga': 'Västmanland',
  // Dalarna
  'Vansbro': 'Dalarna',
  'Malung-Sälen': 'Dalarna',
  'Gagnef': 'Dalarna',
  'Leksand': 'Dalarna',
  'Rättvik': 'Dalarna',
  'Orsa': 'Dalarna',
  'Älvdalen': 'Dalarna',
  'Smedjebacken': 'Dalarna',
  'Mora': 'Dalarna',
  'Falun': 'Dalarna',
  'Borlänge': 'Dalarna',
  'Säter': 'Dalarna',
  'Hedemora': 'Dalarna',
  'Avesta': 'Dalarna',
  'Ludvika': 'Dalarna',
  // Gävleborg
  'Ockelbo': 'Gävleborg',
  'Hofors': 'Gävleborg',
  'Ovanåker': 'Gävleborg',
  'Nordanstig': 'Gävleborg',
  'Ljusdal': 'Gävleborg',
  'Gävle': 'Gävleborg',
  'Sandviken': 'Gävleborg',
  'Söderhamn': 'Gävleborg',
  'Bollnäs': 'Gävleborg',
  'Hudiksvall': 'Gävleborg',
  // Västernorrland
  'Ånge': 'Västernorrland',
  'Timrå': 'Västernorrland',
  'Härnösand': 'Västernorrland',
  'Sundsvall': 'Västernorrland',
  'Kramfors': 'Västernorrland',
  'Sollefteå': 'Västernorrland',
  'Örnsköldsvik': 'Västernorrland',
  // Jämtland
  'Ragunda': 'Jämtland',
  'Bräcke': 'Jämtland',
  'Krokom': 'Jämtland',
  'Strömsund': 'Jämtland',
  'Åre': 'Jämtland',
  'Berg': 'Jämtland',
  'Härjedalen': 'Jämtland',
  'Östersund': 'Jämtland',
  // Västerbotten
  'Nordmaling': 'Västerbotten',
  'Bjurholm': 'Västerbotten',
  'Vindeln': 'Västerbotten',
  'Robertsfors': 'Västerbotten',
  'Norsjö': 'Västerbotten',
  'Malå': 'Västerbotten',
  'Storuman': 'Västerbotten',
  'Sorsele': 'Västerbotten',
  'Dorotea': 'Västerbotten',
  'Vännäs': 'Västerbotten',
  'Vilhelmina': 'Västerbotten',
  'Åsele': 'Västerbotten',
  'Umeå': 'Västerbotten',
  'Lycksele': 'Västerbotten',
  'Skellefteå': 'Västerbotten',
  // Norrbotten
  'Arvidsjaur': 'Norrbotten',
  'Arjeplog': 'Norrbotten',
  'Jokkmokk': 'Norrbotten',
  'Överkalix': 'Norrbotten',
  'Kalix': 'Norrbotten',
  'Övertorneå': 'Norrbotten',
  'Pajala': 'Norrbotten',
  'Gällivare': 'Norrbotten',
  'Älvsbyn': 'Norrbotten',
  'Luleå': 'Norrbotten',
  'Piteå': 'Norrbotten',
  'Boden': 'Norrbotten',
  'Haparanda': 'Norrbotten',
  'Kiruna': 'Norrbotten',
} as const

const REGION_NAME_BY_CODE = new Map(SE_REGIONS.map((r) => [r.code, r.name]))
const COUNTY_BY_NORMALIZED_MUNICIPALITY = new Map(
  Object.entries(SE_COUNTY_BY_MUNICIPALITY).map(([municipality, county]) => [
    normalizeMunicipalityKey(municipality),
    county,
  ]),
)

function normalizeMunicipalityKey(value: string): string {
  return value
    .trim()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/\s+/g, ' ')
}

function stripMunicipalitySuffix(value: string): string {
  const base = value.trim().replace(/\s+kommun$/i, '').trim()
  if (COUNTY_BY_NORMALIZED_MUNICIPALITY.has(normalizeMunicipalityKey(base))) return base
  return base.endsWith('s') ? base.slice(0, -1) : base
}

export function regionNameForRegionCode(regionCode: string): string | null {
  return REGION_NAME_BY_CODE.get(regionCode.toLowerCase()) ?? null
}

export function regionNameForKommun(kommun: string | null | undefined): string | null {
  if (!kommun) return null
  const normalized = normalizeMunicipalityKey(stripMunicipalitySuffix(kommun))
  return COUNTY_BY_NORMALIZED_MUNICIPALITY.get(normalized) ?? null
}
